### ISSUE TITLE
luarocks can't find build dependencies that are installed using `--tree`

### ISSUE THREAD

**Issue by mrcjkb** [luarocks/luarocks#1548]
### Please fill out the following:
- **Platform:**
  - Linux.

- **LuaRocks version:**
  - 3.9.1

- **LuaRocks output from when the issue occurred:**

- See [this workflow run](https://github.com/nvim-neorocks/rocks.nvim/actions/runs/6935248096/job/18865141775#step:4:597)
- See [this issue](https://github.com/nvim-neorocks/rocks.nvim/issues/22#issue-1971518146)

- **Description:**
  - Make sure `luarocks-build-rust-mlua` is **not** installed.
  - `luarocks install toml-edit --tree <some-path>`

**Comment by hishamhm** [comment]
Should be fixed by #1550

**Comment by Freed-Wu** [comment]
Comes from https://github.com/nvim-neorocks/luarocks-tag-release/issues/594

For luarocks 3.12, the bug still occur:

```sh
luarocks install --lua-version=5.1 --tree $(mktemp -d) tellenc.nvim
```

Cannot work.

this project install build_dependency `luanativeobject`, then use `/tmp/tmpXXXX/bin/native_objects` to generate some code. However, `/tmp/tmpXXXX/bin` is not in `$PATH`, which make build failure.

For `--local`, it use `~/.local` as tree, and I have added `~/.local/bin` to `$PATH`, which it can work.
